flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://server/finance-overview-dev
micronaut:
  server:
    multipart:
      max-file-size: 1MB
  application:
    name: financeOverview
  serde:
    serialization:
      inclusion: NON_NULL
jpa:
  default:
    entity-scan:
      packages: com.arclights.finance_overview.persistence.entities
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true